import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BiUserPlus, BiX, BiCheck } from "react-icons/bi";
import Table from "../components/table";

export default function Home() {
	return (
		<section>
			<div className={styles.container}>
				<Head>
					<title>Employee Management System</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className="py-5">
					<h1 className="text-3xl font-bold underline">
						Employee Management System
					</h1>
					<div className="container mx-auto flex justify-between py-5 border-b">
						<div className="left flex gap-3">
							<button className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800">
								Add Employee{" "}
								<span className="px-1">
									<BiUserPlus size={23}></BiUserPlus>
								</span>
							</button>
						</div>
					</div>
					<div className="container mx-auto">
						<Table></Table>
					</div>
				</main>
			</div>
		</section>
	);
}
